name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install monorepo dependencies
        run: npm ci
      - name: Install package dependencies
        run: npx lerna bootstrap
      - name: Run tests
        run: npx lerna run ci
